export enum CourseFormat {
  PDF = 'PDF',
  VIDEO = 'VIDEO',
  CAPSULE = 'CAPSULE'
}

export interface Course {
  id?: number;  // Optional because it is generated by the backend
  courseName: string;
  courseDescription: string;
  courseFormat: CourseFormat;
  pointsEarned: number;
  createdAt?: string;  // Optional because it is managed by the backend
  updatedAt?: string;
  fileData?: Blob;  // For storing PDF, Video, etc.
  fileName?: string;  // Optional: To store the file name for reference
  fileType?: string;  // Optional: To store the file type for reference
}